services:
  postgres:
    container_name: samaysafar-db
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: prerna
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: samaysafardb

volumes:
  :
